const restroList = [
  {
    id: 1,
    img: "gp1ityra6utvzqn6ghnv",
    restoName: "Paradise",
    restoForTwo: 40000,
    rating: "4.0",
    cusine: ["South Indian", "North Indian"],
  },
  {
    id: 2,
    img: "vkhcohhmqfczycw9vsar",
    restoName: "Santosh Family Dhabha",
    restoForTwo: 30000,
    rating: "4.2",
    cusine: ["South Indian", "North Indian"],
  },
  {
    id: 3,
    img: "mt2aggiscfl3yviatwng",
    restoName: "Bakes and Cakes",
    restoForTwo: 20000,
    rating: "4.4",
    cusine: ["Breads", "Cakes"],
  },
  {
    id: 4,
    img: "eohdm5sdnq6e2u46xeux",
    restoName: "Dominos",
    restoForTwo: 40000,
    rating: "4.2",
    cusine: ["Italian", "Pizza"],
  },
  {
    id: 5,
    img: "vkhcohhmqfczycw9vsar",
    restoName: "Sitra Coffee House",
    restoForTwo: 40000,
    rating: "4.6",
    cusine: ["South Indian", "North Indian"],
  },
  {
    id: 6,
    img: "gp1ityra6utvzqn6ghnv",
    restoName: "Paradise",
    restoForTwo: 40000,
    rating: "4.0",
    cusine: ["South Indian", "North Indian"],
  },
  {
    id: 7,
    img: "vkhcohhmqfczycw9vsar",
    restoName: "Santosh Family Dhabha",
    restoForTwo: 30000,
    rating: "4.2",
    cusine: ["South Indian", "North Indian"],
  },
  {
    id: 8,
    img: "mt2aggiscfl3yviatwng",
    restoName: "Bakes and Cakes",
    restoForTwo: 20000,
    rating: "4.4",
    cusine: ["Breads", "Cakes"],
  },
  {
    id: 9,
    img: "eohdm5sdnq6e2u46xeux",
    restoName: "Dominos",
    restoForTwo: 40000,
    rating: "4.0",
    cusine: ["Italian", "Pizza"],
  },
  {
    id: 10,
    img: "vkhcohhmqfczycw9vsar",
    restoName: "Sitra Coffee House",
    restoForTwo: 40000,
    rating: "4.6",
    cusine: ["South Indian", "North Indian"],
  },
];

export default restroList;
